### ISSUE TITLE
Show ambushes on /join and login

### ISSUE THREAD

**Issue by docwhat** [jjasghar/lita-ambush#10]
When a user logins in or `/join`s a channel I expected the ambush to be displayed.

**Comment by jjasghar** [comment]
makes sense, but if you look at the original [hubot plugin](https://github.com/hubot-scripts/hubot-ambush), you'll see that it's when someone says something. PRs accepted though :D

**Comment by liz-baker** [comment]
@docwhat there's also the issue of people's clients that auto connect them, they may not even be looking at it when it shows the message if you key off of `/join`.

**Comment by docwhat** [comment]
@dosman711 I'd say that is a non-issue, since their client will still get it and (potentially) act on it. (e.g. highlight it, create a notification, etc.).
