### ISSUE TITLE
Usage needs to be updated

### ISSUE THREAD

**Issue by jjasghar** [jjasghar/lita-ambush#4]
https://github.com/jjasghar/lita-ambush#usage

it actually says:

```
13:44 <j^2> j2bot: ambush dosman711: you smell like a ferret 
13:44 <j2bot> j^2 I've stored the ambush
13:44 <dosman711> ferrets are cute
13:44 <j2bot> dosman711: While you were out, j^2 said: you smell like a ferret
```

**Comment by liz-baker** [comment]
Actually changed the colon to be optional with PR #5 , but usage will still need to be updated to reflect that.

**Comment by jjasghar** [comment]
Updated via 9faa6723207112ad8e4c4b8b2fa59755873bb8ca
